import { PUBLIC_IMAGE } from "../../asset/images/images";

export const locationData = [
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
  {
    img: PUBLIC_IMAGE.img1,
    location: "한국 용산구",
    score: "4.88",
    view: "도시",
    day: "1월 1일~6일",
    price: "171,177",
  },
  {
    img: PUBLIC_IMAGE.img2,
    location: "한국 서울",
    score: "4.91",
    view: "호수 및 강",
    day: "1월 8일~13일",
    price: "178,024",
  },
  {
    img: PUBLIC_IMAGE.img3,
    location: "한국 중구",
    score: "4.94",
    view: "도시",
    day: "1월 6일~11일",
    price: "196,106",
  },
  {
    img: PUBLIC_IMAGE.img4,
    location: "한국 용산구",
    score: "4.92",
    view: "강변",
    day: "1월 1일~6일",
    price: "183,413",
  },
];
